FROM docker.io/library/golang:1.25.10-alpine AS build
WORKDIR /source
COPY main.go config.go pgbouncer.ini ./
RUN CGO_ENABLED=0 go build -trimpath -o /gateway-launch main.go config.go

FROM docker.io/library/alpine:3.23
RUN apk upgrade --no-cache libcrypto3 libssl3 \
    && apk add --no-cache pgbouncer=1.25.1-r0 \
    && addgroup -S -g 10001 relay \
    && adduser -S -D -H -u 10001 -G relay relay
COPY --from=build /gateway-launch /usr/local/bin/gateway-launch
USER 10001:10001
ENV GOMEMLIMIT=32MiB
EXPOSE 6432
CMD ["/usr/local/bin/gateway-launch"]
